version: '2'
services:

  app:
    # image: 903045850431.dkr.ecr.us-east-1.amazonaws.com/laravel-php:latest
    image: laravel-php:latest
    volumes:
      - ./:/var/www/html/
      - $HOME/.composer/:$HOME/.composer/
  web:
    image: nginx:1.13-alpine
    volumes_from:
      - app
    ports:
      - 8080:80
